apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: cka
spec:
  type: ClusterIP
  selector:
    name: myapp
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: cka
  labels:
    name: myapp
spec:
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
        - name: myapp
          image: kalbyimanie/go:20-merge-f5d59cbc948704f96490e620d3f5617856c58b99
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "50Mi"
              cpu: "100m"
            limits:
              memory: "50Mi"
              cpu: "100m"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: myapp-cm
              mountPath: /etc/config
              readOnly: true
      # tolerations:
      # - key: cluster
      #   operator: "Exists"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - app1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: myapp-pvc
        - name: myapp-cm
          configMap:
            name: myapp-cm
