version: "3.8"
services:  
  dockerd-proxy:
    container_name: dockerd-proxy
    hostname: dockerd-proxy
    image: alpine/socat
    ports:
      - 2376:2375
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    networks: 
      - ansible

# REVIEW needs to enable jenkins secured-login 

  jenkins-master:
    container_name: jenkins-master
    hostname: jenkins-master
    build: 
      context: .
      dockerfile: jenkins.Dockerfile
    environment: 
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Duser.timezone=Asia/Jakarta
      - DOCKER_HOST=tcp://dockerd-proxy:2375
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./casc-configs/jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
    env_file: 
      - ./casc-configs/jenkins.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks: 
      - ansible

networks:
  ansible:
    driver: bridge