version: "3.8"
services:
# REVIEW: SECTION dockerd-proxy
  dockerd-proxy:
    links:
      - vault
      - jenkins-master
    user: root
    container_name: dockerd-proxy
    hostname: dockerd-proxy
    image: alpine/socat
    ports:
      - 2376:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: >
      tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    networks:
      - cicd

# REVIEW: SECTION vault
  vault:
    links:
      - dockerd-proxy
      - jenkins-master
    cap_add:
      - IPC_LOCK
    container_name: vault
    hostname: vault
    image: vault:1.9.0
    environment:
      - VAULT_ADDR='http://0.0.0.0:8200'
    command: ["server", "-config=/vault/config.hcl"]
    ports:
      - 8200:8200
      - 8201:8201
    volumes:
      - ./vault-data/file:/vault/file
      - ./vault-data/log:/vault/log
      - ./vault-config/config.hcl:/vault/config.hcl
    networks:
      - cicd

# NOTE needs to enable jenkins secured-login
# REVIEW: SECTION jenkins-master
  jenkins-master:
    links:
      - dockerd-proxy
      - vault
    depends_on:
      - dockerd-proxy
      - vault
    user: root
    container_name: jenkins-master
    hostname: jenkins-master
    build:
      context: .
      dockerfile: jenkins.Dockerfile
      args:
        - JENKINS_VERSION=2.415
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Duser.timezone=Asia/Jakarta
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./casc-configs/jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./plugins2.txt:/usr/share/jenkins/ref/plugins.txt
    env_file:
      - ./casc-configs/jenkins.env # create your own jenkins.env for the credentials at jenkins startup
    networks:
      - cicd

# REVIEW: SECTION container network
networks:
  cicd:
    driver: bridge
