version: "3.8"
services:
  gnupg:
    container_name: encryptor
    hostname: encryptor
    build:
      context: .
      dockerfile: encryptor.Dockerfile
      # NOTE: arguments variables will be used at build-time
      args:
        # !!! IMPORTANT !!! <REQUIRED FIELDS>
        - KEY_GENERATOR_CONFIG=generate-key-config.txt
        - FILE_TO_ENCRYPT=jenkins.env
        - OUTPUT_OF_ENCRYPTED_FILE=jenkins.env.enc
        - USE_EXISTING_KEY=no
        # - USE_EXISTING_KEY=yes

    # NOTE: environment variables will be used at run-time
    environment:
      # !!! IMPORTANT !!! <REQUIRED FIELDS>
      - KEY_GENERATOR_CONFIG=generate-key-config.txt
      - FILE_TO_ENCRYPT=jenkins.env
      - OUTPUT_OF_ENCRYPTED_FILE=jenkins.env.enc
      - USE_EXISTING_KEY=no
      # - USE_EXISTING_KEY=yes
    # NOTE: uncomment the following line for debugging mode
    # command: ["/bin/bash", "-c", "tail -f /dev/null"]
    volumes:
      - ./data:/data:rw
    networks:
      - cicd

# SECTION container network
networks:
  cicd:
    driver: bridge
