apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - name: http-port
      port: 8083
      targetPort: http-port
      nodePort: 30000
  selector:
    app: jenkins