apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: localhost:5000/jenkins-master-local:latest
        imagePullPolicy: Always
        resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
        env:
          - name: JAVA_OPTS
            value: "-Djenkins.install.runSetupWizard=false -Duser.timezone=Asia/Jakarta"
          - name: CASC_JENKINS_CONFIG
            value: "/var/jenkins_home/casc_configs/jenkins.yaml"
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_vol
      volumes:
        - name: jenkins-vol
          emptyDir: {}