version: "3.8"
services:
  vault-server:
    cap_add:
      - IPC_LOCK
    container_name: vault-server
    hostname: vault-server
    image: vault:1.6.1
    environment: 
      # NOTE config file accepts json or hcl file extension
      - VAULT_LOCAL_CONFIG=/vault/config/config.hcl
      - VAULT_DEV_ROOT_TOKEN_ID=dev
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:1234 
    networks:
      - ansible
    volumes:
      - ./vault/logs:/vault/logs
      - ./vault/file:/vault/file
      - ./vault/config:/vault/config

networks:
  ansible:
    driver: bridge