version: '3.8'
services:
  vault:
    cap_add:
      - IPC_LOCK
    container_name: vault
    hostname: vault
    image: vault:1.9.0
    environment:
      - VAULT_ADDR='http://0.0.0.0:8200'
    command: ["server", "-config=/vault/config.hcl"]
    ports:
      - 8200:8200
      - 8201:8201
    volumes:
      - ./data/file:/vault/file
      - ./data/log:/vault/log
      - ./config/config.hcl:/vault/config.hcl
