version: "3.8"
services:
  ubuntu:
    container_name: "ubuntu"
    image: "ubuntu:xenial"
    volumes:
      - "./hello.sh:/home/hello.sh:rw"
    environment:
      - "PATH=${PATH}:/home"
    command:
      - /bin/bash
      - -c
      - tail -f /dev/null
