version: "3.8"
services:
  nginx-server:
    container_name: nginx-server
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    networks:
      - web-dev
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
  web-app:
    container_name: web-app
    image: web-app:v1
    networks:
      - web-dev
    ports:
      - "80"

#user-defined network for container network
networks:
  web-dev:
    driver: bridge
