version: "3.8"
services:
  web1:
    container_name: web1
    # image: nginx:alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - tugas
  web2:
    container_name: web2
    image: nginx:alpine
    ports:
      - 8081:80
    networks:
      - tugas
networks:
  tugas:
    driver: bridge
