credentials:
  system:
    domainCredentials:
    - credentials:
      - vaultTokenCredential:
          description: "vault-token"
          id: "vault"
          scope: GLOBAL
          token: "{AQAAABAAAAAQgqKN5TBn1mfVFkNDfWOQXQQCob1y+lvxreo+78DpcMc=}"
      - usernamePassword:
          description: "github-account"
          id: "github-account"
          password: "{AQAAABAAAAAQzQ5f/VQZyCMnVEZCdlItR+pncs4DExFayWK8d9q5P9I=}"
          scope: GLOBAL
          username: "username"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - description: "Jenkins administrators"
          entries:
          - user: "admin"
          name: "admin"
          pattern: ".*"
          permissions:
          - "Overall/Administer"
        - description: "developers"
          entries:
          - user: "developers"
          name: "developers"
          pattern: ".*"
          permissions:
          - "Overall/Read"
          - "Job/Read"
        - description: "guest"
          entries:
          - group: "authenticated"
          name: "guest"
          pattern: ".*"
          permissions:
          - "Overall/Read"
          - "Job/Read"
  clouds:
  - docker:
      containerCap: -1
      dockerApi:
        connectTimeout: 120
        dockerHost:
          uri: "tcp://docker.for.mac.host.internal:2376"
        hostname: "dockerd-proxy"
        readTimeout: 60
      exposeDockerHost: true
      name: "docker"
      templates:
      - connector:
          attach:
            user: "root"
        dockerTemplateBase:
          bindAllPorts: true
          environment:
          - "DOCKER_HOST=\"tcp://docker.for.mac.host.internal:2376\""
          environmentsString: "DOCKER_HOST=\"tcp://docker.for.mac.host.internal:2376\""
          hostname: "jenkins-slave"
          image: "localhost:5000/jenkins-slave-local:latest"
          tty: true
          user: "root"
        labelString: "jenkins-slave"
        mode: EXCLUSIVE
        name: "jenkins-slave"
        pullTimeout: 20
        remoteFs: "/home/jenkins"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "hudson.util.DoubleLaunchChecker"
  globalNodeProperties:
  - envVars:
      env:
      - key: "DOCKER_HOST"
        value: "tcp://docker.for.mac.host.internal:2376"
  labelAtoms:
  - name: "built-in"
  - name: "jenkins-slave"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        properties:
        - "apiToken"
        - "mailer"
        - "favorite"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "slack"
        - "theme"
        - "timezone"
        - "experimentalFlags"
      - id: "developers"
        name: "developers"
        properties:
        - "apiToken"
        - "mailer"
        - "favorite"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "slack"
        - "theme"
        - "timezone"
        - "experimentalFlags"
      - id: "guest"
        name: "guest"
        properties:
        - "apiToken"
        - "mailer"
        - "favorite"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "slack"
        - "theme"
        - "timezone"
        - "experimentalFlags"
  slaveAgentPort: 50000
  systemMessage: "### Jenkins configured automatically by Jenkins Configuration as\
    \ Code plugin ###\r\n"
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: true
    usageStatisticsEnabled: true
  extendedSecuritySettings:
    disableLoginAutocomplete: true
    enableXssProtectionHeader: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  sSHD:
    port: 22
  scriptApproval:
    approvedSignatures:
    - "method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object"
unclassified:
  badgePlugin:
    disableFormatHTML: false
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  buildUserVars:
    allBuilds: false
  cacheConfig:
    cacheGetJobs: false
    cacheGetJobsMinutes: 0
  diskUsageProjectActionFactory:
    checkWorkspaceOnAgent: false
    historyLength: 183
    showGraph: true
    timeoutWorkspace: 5
  dockerSettings:
    cloudOrder: "asIs"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost/jenkins/github-webhook/"
  githubPullRequests:
    actualiseOnFactory: false
  globalConfigurationImpl:
    allResults: true
    enabled: true
    notificationTimeout: 15000
    queryTimeout: 30
  globalLibraries:
    libraries:
    - defaultVersion: "master"
      name: "helloWorld"
      retriever:
        modernSCM:
          libraryPath: "docker/jenkins/pipelines/shared-library/"
          scm:
            git:
              id: "de5cb04f-a351-4f24-bbc8-52cff06daa9b"
              remote: "https://github.com/kalbyimanie/devops"
              traits:
              - "gitBranchDiscovery"
  globalTimeOutConfiguration:
    operations:
    - "abortOperation"
    overwriteable: false
  hashicorpVault:
    configuration:
      engineVersion: 2
      timeout: 60
      vaultCredentialId: "vault"
      vaultUrl: "http://vault:8200"
  jobConfigHistory:
    excludePattern: "queue\\.xml|nodeMonitors\\.xml|UpdateCenter\\.xml|global-build-stats|LockableResourcesManager\\\
      .xml|MilestoneStep\\.xml|cloudbees-disk-usage-simple\\.xml"
    saveModuleConfiguration: false
    showBuildBadges: "always"
    showChangeReasonCommentWindow: true
    skipDuplicateHistory: true
  junitTestResultStorage:
    storage: "file"
  locale:
    ignoreAcceptLanguage: false
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://localhost/jenkins/"
  login-theme-plugin:
    useDefaultTheme: true
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  nextBuilds:
    dateFormat: "dd/MM/yyyy HH:mm z"
    displayMode: 1
    filterByView: true
    showParameterizedWidget: false
    showPossibleWidget: false
  pollSCM:
    pollingThreadCount: 10
  prioritySorterConfiguration:
    onlyAdminsMayEditPriorityConfiguration: false
    strategy:
      absoluteStrategy:
        defaultPriority: 3
        numberOfPriorities: 5
  scheduleBuild:
    defaultScheduleTime: "10:00:00 PM"
    timeZone: "Asia/Jakarta"
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  statisticsConfiguration:
    buildInfo: true
    buildStepInfo: true
    projectInfo: true
    queueInfo: true
    scmCheckoutInfo: true
    shouldPublishToAwsSnsQueue: false
    shouldSendApiHttpRequests: false
    shouldSendToLogback: false
  telegramBotGlobalConfiguration:
    approvalType: ALL
    shouldLogToConsole: false
  themeManager:
    disableUserThemes: true
    theme: "darkSystem"
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  whitelist:
    enabled: false
tool:
  git:
    installations:
    - home: "/usr/bin/git"
      name: "git"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
