jenkins:
  authorizationStrategy: "loggedInUsersCanDoAnything"
  clouds:
  - docker:
      containerCap: -1
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "tcp://docker.for.mac.host.internal:2376"
        readTimeout: 60
      errorDuration: 10
      exposeDockerHost: true
      name: "docker"
      templates:
      - connector:
          attach:
            user: "root"
        dockerTemplateBase:
          bindAllPorts: true
          cpuPeriod: 0
          cpuQuota: 0
          environment:
          - "DOCKER_HOST=\"tcp://docker.for.mac.host.internal:2376\""
          environmentsString: "DOCKER_HOST=\"tcp://docker.for.mac.host.internal:2376\""
          hostname: "jenkins-slave"
          image: "kalbyimanie/jenkins:jenkins-slave-local_latest"
          privileged: true
          user: "root"
        instanceCapStr: "1"
        labelString: "jenkins-slave"
        name: "jenkins-slave"
        pullTimeout: 300
        remoteFs: "/home/jenkins"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
  - name: "built-in"
  - name: "jenkins-slave"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - jvmVersion:
      comparisonMode: RUNTIME_GREATER_OR_EQUAL_MASTER_BYTECODE
  - "remotingVersion"
  - "responseTime"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin" # pass: admin
        properties:
        - "apiToken"
        - "consoleUrlProvider"
        - "favorite"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "slack"
        - theme:
            theme: "noOp"
        - "timezone"
        - "experimentalFlags"
        - mailer:
            emailAddress: "admin@sample.com"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  locale:
    ignoreAcceptLanguage: false
    systemLocale: "USE_BROWSER_LOCALE"
  loginTheme:
    useDefaultTheme: true
  monitorConfiguration:
    columns: 2
  pipelineGraphView:
    showGraphOnBuildPage: false
    showGraphOnJobPage: false
  prism:
    theme: PRISM
  themeManager:
    disableUserThemes: false
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  cps:
    hideSandbox: false
  gitHooks:
    allowedOnAgents: true
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
  scriptApproval:
    forceSandbox: false
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  buildUserVars:
    allBuilds: false
  diskUsageProjectActionFactory:
    checkWorkspaceOnAgent: false
    historyLength: 183
    showGraph: true
    timeoutWorkspace: 5
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost/jenkins/github-webhook/"
  githubPullRequests:
    actualiseOnFactory: false
  globalConfigurationImpl:
    allResults: true
    enabled: true
    notificationTimeout: 15000
    queryTimeout: 30
  globalTimeOutConfiguration:
    operations:
    - "abortOperation"
    overwriteable: false
  jobConfigHistory:
    excludePattern: "queue\\.xml|nodeMonitors\\.xml|UpdateCenter\\.xml|global-build-stats|LockableResourcesManager\\\
      .xml|MilestoneStep\\.xml|cloudbees-disk-usage-simple\\.xml"
    saveModuleConfiguration: false
    showBuildBadges: "always"
    showChangeReasonCommentWindow: true
    skipDuplicateHistory: true
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  nextBuilds:
    filterByView: true
    showParameterizedWidget: false
    showPossibleWidget: false
  pollSCM:
    pollingThreadCount: 10
  prioritySorterConfiguration:
    onlyAdminsMayEditPriorityConfiguration: false
    strategy:
      absoluteStrategy:
        defaultPriority: 3
        numberOfPriorities: 5
  scheduleBuild:
    defaultScheduleTime: "22:00:00"
    defaultStartTime: "22:00:00"
    timeZone: "Asia/Jakarta"
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  slackNotifier:
    botUser: false
    sendAsText: false
  telegramBotGlobalConfiguration:
    shouldLogToConsole: true
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  whitelist:
    enabled: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"