version: "3.8"
services:
  es01:
    container_name: es01
    hostname: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.master=true
      - node.data=false
      # - node.ingest=true
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*

    # volumes:
      # - ./jvm.options:/usr/share/elasticsearch/config/jvm.options
      # - ./elasticsearch-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - es

  es02:
    container_name: es02
    hostname: es02
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    # volumes:
      # - ./jvm.options:/usr/share/elasticsearch/config/jvm.options
      # - ./elasticsearch-data.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - es
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.master=false
      - node.data=false
      - node.ingest=true
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "discovery.zen.ping.unicast.hosts=es01"


networks:
  es:
