cluster.name: "docker-cluster"
network.host: 0.0.0.0
node.name: es01
http.port: 9200-9300

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
node.master:  true
node.data: false
node.ingest: false
search.remote.connect: false
# discovery.zen.ping.unicast.hosts: ["es01, es02"]
discovery.zen.minimum_master_nodes: 1
xpack.license.self_generated.type: basic
