cluster.name: "docker-cluster"
network.host: 0.0.0.0
http.port: 9200-9300
node.name: es02
# transport.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.ping.unicast.hosts: ["es01, es02"]
node.master:  false
node.data: true
node.ingest: false
search.remote.connect: false
discovery.zen.minimum_master_nodes: 1
xpack.license.self_generated.type: basic
#discovery.seed_hosts: es01
