apiVersion: v1
kind: Service
metadata:
  name: watcher
  namespace: cka
spec:
  selector:
    name: watcher
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
  namespace: cka
  labels:
    name: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      name: watcher
  template:
    metadata:
      labels:
        name: watcher
    spec:
      containers:
      - name: watcher
        image: kalbyimanie/devops:watcher-v3
        imagePullPolicy: Always
        env:
          - name: SERVICE_NAME
            value: "myapp"
          - name: SERVICE_PORT
            value: "80"
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
      tolerations:
      - key: cluster
        operator: "Exists"
