apiVersion: v1
kind: Service
metadata:
  name: ingress-service
  namespace: ingress-space
spec:
  # clusterIP: 10.110.253.55
  # clusterIPs:
  # - 10.110.253.55
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32203
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    name: nginx-ingress
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
