# This is a basic workflow to help you get started with Actions

name: experiment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  init:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@develop
  build:
    runs-on: ubuntu-latest
    steps:
      - name: go to directory
        run: |
          cd docker/tugas

      - name: build image
        env:
          hashCommit: ${{ GITHUB_SHA }}
        run: |
          docker build -t tugas:$GITHUB_SHA -f cmd.Dockerfile .
