# This is a basic workflow to help you get started with Actions
name: experiment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: develop
      # - name: build image
      #   working-directory: docker/tugas
      #   run: |
      #     docker build -t tugas:$GITHUB_SHA -f cmd.Dockerfile .
      - name: docker login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: build and push image to dockerhub
        id: docker_build
        uses: docker/build-push-action@v2
        # working-directory: docker/tugas
        with:
          context: docker/tugas
          file: ./cmd.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops:v1-${{ GITHUB_SHA }}
