name: experiment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "input branch name"
        required: true
        default: "develop"
      string:
        description: "input arbitrary string"
        required: true
        default: "string"
  push:
    branches:
      - "develop"

jobs:
  sample-docker:
    name: "sample-docker"
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.events.inputs.branch }}
      - id: sample-docker
        name: "exec"
        uses: ./.github/actions/sample-docker
        with:
          string: "${{ github.events.inputs.string }}"
