name: experiment

on:
  workflow_dispatch:
    inputs:
      string:
        description: "[optional] input arbitrary string"
        required: false
        default: "string"
  push:
    branches:
      - "develop"

jobs:
  sample-docker:
    name: "sample-docker"
    runs-on: ubuntu-latest
    steps:
      - id: sample-docker
        name: "exec"
        uses: actions/devops@v1
