apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgresql-client-storage-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer